### ISSUE TITLE
question about postgres settings

### ISSUE THREAD

**Issue by jpinero** [mi-erasmusmc/Dracula#1]
Hi Rowan, 
I am not good with postgres. I have one database for ctti and one for rxnorm, and the settings.toml

pg_dbname = "ctti"
# Drug Reference DB
drug_ref = "rxnorm" 

this table article57_rxnorm gets correctly created, and rxnorm.rxnconso does exist, but I get this error 

thread 'main' panicked at 'Error executing direct_match_rxnconso: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"rxnorm.rxnconso\" does not exist", detail: None, hint: None, position: Some(Original(172)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(1371), routine: Some("parserOpenTable") }) }', src/db/mod.rs:39:10

What do I need to do?

thanks!!

by the way,  "Count Dracula awakens ... " 😂

**Comment by RowanErasmus** [comment]
Hi Janet,

Sorry for the slow response. The script expects the data to be in a single database with two schemas one called rxnorm for the rxnorm data and one called ctgov with the ctti data (I think that is what it is called when you load it from the dump they publish by default)
